

<body onload "loadButtons()">

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
    <div class="container-fluid">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
           aria-expanded="false">
            Topics
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <h6 class="dropdown-header">Physics</h6>
            <a class="dropdown-item" href="/course/l/physics/magnetism">Magnetic Field</a>
            <a class="dropdown-item" href="#">Electric Field</a>
            <a class="dropdown-item" href="#">Planet System</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Chemistry</h6>
            <a class="dropdown-item" href="#">Moledules</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Biology</h6>
            <a class="dropdown-item" href="#">Human Cell</a>
            <div class="dropdown-divider"></div>
            <h6 class="dropdown-header">Mathematics</h6>

        </div>
        <p class="text-left">Xperiment.3D</p>
    </div>
</nav>

<div id="slides" class="carousel slide" data-ride="carousel">
    <ul class="carousel-indicators">
        <li data-target="#slides" data-slide-to="0" class="active"></li>
        <li data-target="#slides" data-slide-to="1"></li>
        <li data-target="#slides" data-slide-to="2"></li>
        <li data-target="#slides" data-slide-to="3"></li>
        <li data-target="#slides" data-slide-to="4"></li>
    </ul>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="img/modl1.png">
            <div class="carousel-caption">
                <h1 class="display-2">Xperiment.3D</h1>
                <h3>Aiming to universalize learning via experimentation in a virtual world</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/phys1.jpg">
            <div class="carousel-caption">
                <h1 class="display-2">Physics Models</h1>
                <h3>"A rainbow is the product of physics working for your appreciation of beauty. "</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/chem1.jpg">
            <div class="carousel-caption">
                <h1 class="display-2">Chemistry Models</h1>
                <h3>"Chemistry states the more energy you put into a bond, the harder it is to break. "</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/biol1.jpg">
            <div class="carousel-caption">
                <h1 class="display-2">Biology Models</h1>
                <h3>"Nothing in biology makes sense except in the light of evolution. "</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img src="img/math1.jpg">
            <div class="carousel-caption">
                <h1 class="display-2">Mathematical Models</h1>
                <h3>"Math is the only place hwere truth and beauty mean the same thing. "</h3>
            </div>
        </div>
    </div>
</div>
<hr class="my-4">

<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12">
            <br>
            <h1 class="display-4">Features</h1>
        </div>
        <hr>
    </div>
</div>

<!--- Features / 3 Column -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <img src="img/hori1.jpg" alt="Feature 1 image" class="img-thumbnail">
            <h3>Feature 1</h3>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <img src="img/hori1.jpg" alt="Feature 2 image" class="img-thumbnail">
            <h3>Feature 2</h3>
        </div>
        <div class="col-sm-12 col-md-4">
            <img src="img/hori1.jpg" alt="Feature 3 image" class="img-thumbnail">
            <h3>Feature 3</h3>
        </div>
    </div>
    <hr class="my-4">
</div>


<!--- Physics / Cards --->
<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-8">
            <div class="text-center">
                <h1 class="display-4">Physics</h1>
                <p class="lead"><em>Some physics quote / importance</em></p>
            </div>
            <div class="row padding">
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Magnetic Field</h4>
                            <a href="/course/l/physics/magnetism" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Electric Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Planet System</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <img src="img/vert1.jpg" alt="Feature 1 image" class="img-thumbnail">
            <br>
            <br>
            <button type="button" class="btn btn-primary btn-lg btn-block">Browse More</button>
        </div>
    </div>
</div>
<hr class="my-4">

<!--- Physics / Cards --->
<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-8">
            <div class="text-center">
                <h1 class="display-4">Chemistry</h1>
                <p class="lead"><em>Some physics quote / importance</em></p>
            </div>
            <div class="row padding">
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Magnetic Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Electric Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Planet System</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <img src="img/vert1.jpg" alt="Feature 1 image" class="img-thumbnail">
            <br>
            <br>
            <button type="button" class="btn btn-primary btn-lg btn-block">Browse More</button>
        </div>
    </div>
</div>
<hr class="my-4">


<!--- Physics / Cards --->
<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-8">
            <div class="text-center">
                <h1 class="display-4">Biology</h1>
                <p class="lead"><em>Some physics quote / importance</em></p>
            </div>
            <div class="row padding">
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Magnetic Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Electric Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Planet System</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <img src="img/vert1.jpg" alt="Feature 1 image" class="img-thumbnail">
            <br>
            <br>
            <button type="button" class="btn btn-primary btn-lg btn-block">Browse More</button>
        </div>
    </div>
</div>
<hr class="my-4">


<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-8">
            <div class="text-center">
                <h1 class="display-4">Math</h1>
                <p class="lead"><em>Some physics quote / importance</em></p>
            </div>
            <div class="row padding">
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Magnetic Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Electric Field</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-flex align-items-stretch">
                    <div class="card">
                        <img class="card-img-top" src="img/vert1.jpg">
                        <div class="card-body">
                            <h4 class="card-title">Planet System</h4>
                            <a href="#" class="btn btn-outline-secondary">Get Started</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            <img src="img/vert1.jpg" alt="Feature 1 image" class="img-thumbnail">
            <br>
            <br>
            <button type="button" class="btn btn-primary btn-lg btn-block">Browse More</button>
        </div>
    </div>
</div>
<hr class="my-4">

<!--- Connect -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-12">
            <h2>Connect</h2>
        </div>
        <div class="col-12 social padding">
            <a href="#">
                <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
                <i class="fab fa-google-plus-g"></i>
            </a>
            <a href="#">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
                <i class="fab fa-youtube"></i>
            </a>
        </div>
    </div>
</div>

</body>
</html>