<!DOCTYPE html>
<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
$vdata=$this->view_data;

?>
<html>
<head>

    <title><?php echo $vdata["title"]?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="/js/three/three.js"></script>
    <script  src="/js/three/GLTFLoader.js"></script>
    <script  src="/js/three/OrbitControls.js"></script>
    <script  src="/js/three/DRACOLoader.js"></script>

    <link href="https://fonts.googleapis.com/css2?family=Alegreya&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">

    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js">

    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js">

    </script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js">

    </script>
    <?php

    //    Dynamically loaded scripts from viewdata
    if(isset($vdata["scripts"])) {
        foreach ($vdata["scripts"] as $script) {
            if(is_array($script)){
                foreach ($script as $sc){
                    if(file_exists("js" .DIRECTORY_SEPARATOR. $sc )) {
                        echo "<script src='/js" . DIRECTORY_SEPARATOR . $sc . "'></script>";
                    }else{
                        echo "<script src='".$sc."'></script>";
                    }
                }
            }else{
                if(file_exists("js" .DIRECTORY_SEPARATOR. $script )) {
                    echo "<script src='/js" . DIRECTORY_SEPARATOR . $script . "'></script>";
                }else{
                    echo "<script src='".$script."'></script>";
                }}
        }
    }

//    Dynamically loaded stylesheets from viewdata
    if(isset($vdata["stylesheets"])) {
        foreach ($vdata["stylesheets"] as $stylesheet) {
            if(is_array($stylesheet)) {
                foreach ($stylesheet as $st) {
                    if (file_exists("css" . DIRECTORY_SEPARATOR . $st)) {
                        echo "<link href='/css" . DIRECTORY_SEPARATOR . $st . "' rel='stylesheet'>";
                    } else {
                        echo "<link href='" . $st . "' rel='stylesheet'>";
                    }
                }
            }else{
                    if (file_exists("css" . DIRECTORY_SEPARATOR . $stylesheet)) {
                        echo "<link href='/css" . DIRECTORY_SEPARATOR . $stylesheet . "' rel='stylesheet'>";
                    } else {
                        echo "<link href='" . $stylesheet . "' rel='stylesheet'>";

                    }
                }

        }
    }


    ?>

</head>





