


<body onload="loadButtons()">

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
    <div class="container-fluid">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            PHYS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Topic1</a>
            <a class="dropdown-item" href="#">Topic2</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
        <a href="/">Xperiment.3D</a>
    </div>
</nav>

<!--- Welcome Section -->
<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12">
            <h1 class="display-4">Physics</h1>
        </div>
        <hr>
        <div class="col-12">
            <p class="lead"><em>"When you change the way you look at things, the things you look at change. "</em></p>
        </div>
    </div>
</div>

<!--- Three Column Section -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <h3>Magnetism</h3>
            <button id="btn" type="button" class="btn btn-primary btn-sm btn-block">Topic1</button>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4">
            <h3>Electrostatics</h3>
            <button type="button" class="btn btn-primary btn-sm btn-block">Topic1</button>
        </div>
        <div class="col-sm-12 col-md-4">
            <h3>Kinematics</h3>
            <button type="button" class="btn btn-primary btn-sm btn-block">Topic1</button>
        </div>
    </div>
    <hr class="my-4"
</div>

<!--- Connect -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-12">
            <h2>Connect</h2>
        </div>
        <div class="col-12 social padding">
            <a href="#">
                <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
                <i class="fab fa-google-plus-g"></i>
            </a>
            <a href="#">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
                <i class="fab fa-youtube"></i>
            </a>
        </div>
    </div>
</div>

</body>
</html>